#!/usr/bin/env bash
# A script that Install and configure nginx web server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo nginx restart
