#!/usr/bin/env bash
# This is a script that Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8

sudo apt-get -y update
sudo apt-get install -y haproxy=2.8.\*

# To configure HAProxy load balance 
echo "frontend http
	bind *:80
	mode http
	default_backend web-backend
    backend web-backend
	balance roundrobin
	server 257227-web-01 54.237.46.62:80 check
	server 257227-web-02 18.206.208.30:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
