#!/usr/bin/env bash
# This a Bash script that generates a MySQL dump and creates a compressed archive out of it.

today=$(date +%d-%m-%y)
sudo mysqldump -u root -p$1 --all-databases > backup.sql
file="$today.tar.gz"
tar -czvf $file backup.sql
