#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours amd 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59

i=0
m=1

while [ $i -le 12 ]
do 
	echo "Hour: $i"

	m=1
	while [ $m -le 59 ]
	do
		echo "$m"
		((m++))
	done
	i=$((i+1))
done
