#!/usr/bin/env bash
# To  Bash script that accepts one argument and the script
# should run the whoami command under the user passed as an argument
# The -u option specifies the user
USER=$1
sudo -u "$USER" whoami
