#!/usr/bin/env bash
# A bash script that fix some short and sweet

# sudo chmod 744 /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
